### ISSUE TITLE
.NET Core not detected

### ISSUE THREAD

**Issue by JorgeLM97** [vixark/RTS-Helper#5]
I get the following error message "To run this application, you must install .NET Core. Would you like to download it now?"
When clicking [Yes ] nothing happens and the app closes.
I installed "aspnetcore-runtime-3.1.32-win-x64.exe", 
"dotnet-runtime-3.1.32-win-x64.exe", "windowsdesktop-runtime-3.1.32-win-x86.exe" from Microsoft and installed them but that didn't fix it. Which version of .NET Core is required? Where can I download it? Maybe this info could be added to the readme or somewhere else.

**Comment by vixark** [comment]
Hello,  It needs .NET Core 3.1 to run.

Are you trying to run it from code or from the executable?

**Comment by JorgeLM97** [comment]
I'm running from the executable provided at http://vixark.com/rts-helper, it works now, I just noticed I installed the x86 version instead of the x64 one before... That might have been it. After installing the x64 version it works correctly. Anyways, maybe that link could be added to the readme to make it clearer? The update prompt that opens when not having .NET Core installed still doesn't work. I'm running W10 Pro 10.0.19045 if its relevant.

**Comment by vixark** [comment]
The file in vixark.com is compiled as 'Any CPU' so it should work the same in x86 or x64. Strange that your computer decided to choose x86. 

About the update promt, that is automatic from Windows and .Net framework. I don't have control of it.

Anyway, It's good to hear that it worked. I hope you enjoy it. 

If you have any further question I can help you out.
